// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPsIN3AUHcA25UKfB4uOccd-RT2SWWSGc',
    appId: '1:857641955856:android:627fd7d3fedb0c66899095',
    messagingSenderId: '857641955856',
    projectId: 'care-clinic-4933b',
    databaseURL: 'https://care-clinic-4933b-default-rtdb.firebaseio.com',
    storageBucket: 'care-clinic-4933b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMDeKYHGgx5b-ZAroafJn46Xh_xLSKAnE',
    appId: '1:857641955856:ios:2d0d6cc3f220a3b3899095',
    messagingSenderId: '857641955856',
    projectId: 'care-clinic-4933b',
    databaseURL: 'https://care-clinic-4933b-default-rtdb.firebaseio.com',
    storageBucket: 'care-clinic-4933b.firebasestorage.app',
    iosBundleId: 'com.example.careClinic',
  );

}